# Generated by Django 6.0.3 on 2026-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transport', models.CharField(choices=[('電車', 'Train(電車)'), ('バス', 'Bus(バス)')], max_length=10)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('trip_type', models.CharField(choices=[('往復', 'Round Trip(往復)'), ('片道', 'One Way(片道)')], max_length=10)),
                ('purpose', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
