# Generated by Django 6.0.3 on 2026-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_transport_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transport',
            field=models.CharField(choices=[('電車', 'Train(電車)'), ('バス', 'Bus(バス)'), ('電車＋バス', 'Train + Bus(電車＋バス)'), ('タクシー', 'Taxi(タクシー)'), ('その他', 'Other(その他)')], max_length=10),
        ),
    ]
